{
 "title": "FRITZ!Box Status",
 "description": "Monitor FRITZ!Box routers using prometheus and fritzbox_exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gateway_device_modelname" }
   ]
  },
  {
   "title": "Fritzbox Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_uptime_seconds{service=\"Device\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_uptime_seconds{service=\"WANIPConnection\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "gateway_data_ecostat_cputemp", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_traffic_rate{direction=\"Received\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_traffic_rate{direction=\"Sent\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ]
    }
   ]
  },
  {
   "title": "WAN Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "2,4 GHz Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wlan_current_connections{frequency=\"2.4 GHz\"}"
    }
   ]
  },
  {
   "title": "5 GHz Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wlan_current_connections{frequency=\"5 GHz\"}"
    }
   ]
  },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_layer1_link_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "dslstatus" }
     ]
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_traffic{direction=\"Received\", unit=\"Bytes\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Energy consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gateway_data_energy_consumption",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "gateway_data_ecostat_cpuutil", "legendFormat": "CPU" },
    { "expr": "gateway_data_ecostat_ramusage", "legendFormat": "RAM {{ram_type}}" }
   ]
  },
  {
   "title": "Total Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_traffic{direction=\"Sent\", unit=\"Bytes\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "Network Devices",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gateway_host_active" }
   ]
  },
  {
   "title": "Download Bandwith Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream",
     "expr": "gateway_max_bitrate{direction=\"Down\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max. Downstream",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'receiverate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-receiverate,'downstream')"
    },
    {
     "alias": "upstream",
     "expr": "gateway_wan_traffic_rate{direction=\"Received\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Download",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'sendrate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-sendrate,'upstream')"
    }
   ]
  },
  {
   "title": "Upload Bandwith Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream max",
     "expr": "gateway_max_bitrate{direction=\"Up\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Upstream",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'downstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "downstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-downstreammax,'downstream max')"
    },
    {
     "alias": "upstream max",
     "expr": "gateway_wan_traffic_rate{direction=\"Sent\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Upload",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'upstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "upstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-upstreammax,'upstream max')"
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(gateway_wan_traffic{direction=\"Received\", unit=\"Bytes\"}[$__interval])",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  }
 ]
}